# Generated by Django 5.1.2 on 2024-11-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalStudent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='StudentRegNumber',
            field=models.IntegerField(unique=True),
        ),
    ]
