# Generated by Django 5.1.2 on 2024-11-29 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalStudent', '0003_alter_student_contactmobilenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='StatusOftheSemesterFee',
            field=models.BooleanField(default=False),
        ),
    ]
